### your site title here

title: Seojin Lee
description: Ph.D. student | Stanford University | Vision Science & Computational Modeling
remote_theme: jitinnair1/gradfolio

nav:
  - name: "Home"
    link: /
  - name: "Research"
    link: /research/
  - name: "Curiosity"
    link: /curiosity/
  - name: "Life outside academia"
    link: /lifeoutsideacademia/


baseurl: ""    # empty because this is your main site, not inside a subfolder
url: "https://slee20512.github.io"
email: seojinl@stanford.edu

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
googlescholar: "https://scholar.google.com/citations?user=yzh-miEAAAAJ&hl=en"
linkedin: "https://www.linkedin.com/in/seojin-lee-95b76b223/"
# stackoverflow: "#"
github: "https://github.com/slee20512"
# researchgate: "#"
# orcid: "#"
# quora: "#"
# instagram: "#"
# facebook: "#"
# bluesky: "#"

# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - shortProject.md
      - longerProjectTitle.md
      - redirect.md
      - project4.md
      - project5.md
      - project6.md

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
